#!/bin/bash
STOREPASS="forgotten2"
for ENT in server2_J client5_J client6_J client7_J client8_J ;
do
 rm -f ${ENT}.jks ${ENT}.pem
   echo -e "${ENT}\nDEI\nISEP\nPORTO\nPORTO\nPT\nyes" | keytool -genkey -v -alias ${ENT} -keyalg RSA -keysize 2048 \
	-validity 365 -keystore ${ENT}.jks -storepass ${STOREPASS}
 keytool -exportcert -alias ${ENT} -keystore ${ENT}.jks -storepass ${STOREPASS} -rfc -file ${ENT}.pem
done
####
echo "Creating trust relations"

for ENT in client5_J client6_J client7_J client8_J;

do
 echo "yes"|keytool -import -alias ${ENT} -keystore server2_J.jks -file ${ENT}.pem -storepass ${STOREPASS}
 echo "yes"|keytool -import -alias server2_J -keystore ${ENT}.jks -file server2_J.pem -storepass ${STOREPASS}
done

echo "yes"|keytool -import -alias server2_J -keystore client4_J.jks -file server2_J.pem -storepass ${STOREPASS}
echo "############################################################################"
keytool -list -keystore server2_J.jks -storepass ${STOREPASS}
echo "############################################################################"
echo "WARNING: For testing, client4_J is not added to the list of authorized clients"
echo "############################################################################"
#######